from .crypto import do_crypto
from  .facebook import do_facebook
from .hackathon import do_hackathon
from .movie import do_movie
from .news import do_news
from .quote import do_quote
from  .stocks import do_stocks
from .wallpaper import do_wallpaper
from  .wiki import do_wiki
from .youtube import do_youtube